### ISSUE TITLE
question about b and k

### ISSUE THREAD

**Issue by userrand** [rdavison/graphite-layout#1]
The text below was written with graphite (: . 

Thank you for sharing this great keyboard layout and the great readme with the stats, explanations, mentions and everything. 

I am curious about the choice for k and b. 

 I am learning to touch type and I notice that the k is easy to type although it is a rare letter while the b is hard to type (or hard to find when learning to touch type) and is more common than k.

 Is there a drawback to switching k and b that could be noticed without trying the different analyzers? 

Or an analyzer whose results could be interpreted as "switching k and b is a bad idea because  ..." where ... is something fairly specific to that particular change such as common trigrams where k and b occur ?

**Comment by rdavison** [comment]
The problem with swapping K and B would mostly be that you would have K and N on the same finger, and that finger is pinky. So think of all the common words you know that use KN:

```
Examples of kn:
167,595 / 81,369,938 words (0.206%)

know            (85157)
known           (21164)
knowledge       (12420)
knew            (11418)
knows           (7484)
knowing         (5300)
unknown         (2327)
knife           (2055)
knee            (1542)
darkness        (1350)
```

```
Examples of nk:
211,595 / 81,369,938 words (0.260%)

think           (70451)
thanks          (18985)
thinking        (12277)
bank            (11393)
thank           (11035)
link            (9849)
links           (5764)
drink           (5680)
banks           (4602)
tank            (3945)
```

Here are some variations for moving B off pinky:

```
graphite
  b l d w z  ' f o u j ; =
  n r t s g  y h a e i ,  
  q x m c v  k p . - /    

SHAI:
  Alt: 32.22%
  Rol: 41.46%   (In/Out: 20.48% | 20.98%)
  One:  1.57%   (In/Out:  0.46% |  1.11%)
  Red:  1.96%   (Bad:     0.25%)

  SFB: 0.93%
  SFS: 5.19%    (Red/Alt: 0.62% | 4.57%)

  LH/RH: 47.99% | 52.01%

```
graphite (bk swap)
  k l d w z  ' f o u j ; =
  n r t s g  y h a e i ,  
  q x m c v  b p . - /    

SHAI:
  Alt: 31.49%
  Rol: 41.79%   (In/Out: 20.10% | 21.69%)
  One:  1.70%   (In/Out:  0.45% |  1.25%)
  Red:  1.83%   (Bad:     0.24%)

  SFB: 1.05%
  SFS: 5.34%    (Red/Alt: 0.84% | 4.50%)

  LH/RH: 47.38% | 52.62%
```

```
graphite (bz swap)
  z l d w b  ' f o u j ; =
  n r t s g  y h a e i ,  
  q x m c v  k p . - /    

SHAI:
  Alt: 31.90%
  Rol: 41.36%   (In/Out: 20.02% | 21.34%)
  One:  1.57%   (In/Out:  0.46% |  1.11%)
  Red:  1.94%   (Bad:     0.24%)

  SFB: 0.98%
  SFS: 5.50%    (Red/Alt: 0.62% | 4.88%)

  LH/RH: 47.99% | 52.01%
```

You can also try exploring your swap ideas on:
- Oxey's layout playground: https://o-x-e-y.github.io/layouts/playground/index.html
- Clemenpine's keysolve: https://clemenpine.github.io/keysolve-web/

**Comment by userrand** [comment]
amazingly fast and detailed reply. Thank you very much for your thorough answer and links.

**Comment by userrand** [comment]
The mb from the b z switch does not seem too bad as it seems to be a rare bigram. I am also not too bothered by a heavy left index finger but that is probably because I am typing very very slowly as I am learning.

But i am not sure whether the position of the b or the z is more difficult on the graphite layout. I should continue practicing to know which is easier.

**Comment by rdavison** [comment]
Another concern I have with the back swap is the distance between `b` and `c` is pretty high. For example, try typing the words `because`, `back`, `become`, `facebook`, `cable`.

**Comment by userrand** [comment]
Indeed at least as a beginner learning to touch type those large distances feel a bit closer to qwerty and might be harder to coordinate when typing quickly.
